### ISSUE TITLE
dockercompose exec web npm installを実行するとエラーになる。

### ISSUE THREAD

**Issue by tyamori** [shonansurvivors/laravel-fargate-app#28]
はじめまして「TerraformでFargateを構築してGithub Actionでデプロイ」を購入させて頂き、現在第一章を進めさせて頂いているのですが、1.5.3にて
dockercompose exec web npm install
を実行すると以下のエラーが表示され完了出来ません。

Error relocating /usr/local/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEv: symbol not found
Error relocating /usr/local/bin/node: _ZSt28__throw_bad_array_new_lengthv: symbol not found

調べたところ、Dockerfileに以下の記述を足すことで改善されたという記事があったので
試してみたのですが、残念ながら状況は改善されませんでした。
RUN apk add --no-cache --virtual g++
RUN apk add --no-cache libstdc++ && apk add --no-cache libgcc

お手数お掛けいたしますが、ご助言頂けますと幸いです。

以上よろしくお願いします。

**Comment by shonansurvivors** [comment]
原因はまだ判明していないのですが、取り急ぎ

```
docker-compose exec web npm install
```

とあるところは、

```
cd backend
```

し、

```
npm install
```

としていただけますでしょうか？

同様に

```
docker-compose exec web npm run dev
```

とあるところも

```
npm run dev
```

としていただければと思います。

**Comment by tyamori** [comment]
頂いたコマンドの方でnpmのインストールと実行が出来ました。
お忙しいところ、早速のお返事ありがとうございました。
